### ISSUE TITLE
Removed container maintenance window not detected

### ISSUE THREAD

**Issue by pdecat** [terraform-providers/terraform-provider-google#1675]
The google provider does not detect when the maintenance window of a container cluster was removed out of band.

I've tested google provider versions from 1.14.0 all the way back to 1.4.0 and none detected the drift.

### Terraform Version

```
terraform version
Terraform v0.11.7
+ provider.google v1.14.0
```

### Affected Resource(s)

- google_container_cluster

### Terraform Configuration Files

```hcl
resource "google_container_cluster" "gke_cluster" {
  name = "myproject-europe-west1-cluster"
  zone = "europe-west1-b"

  node_pool {
    node_count = 1
  }

  maintenance_policy {
    daily_maintenance_window {
      start_time = "08:00"
    }
  }
}
```

### Debug Output

TODO

### Panic Output

N/A

### Expected Behavior

The out of band removal of the maintenance window should be detected during plan.

### Actual Behavior

The out of band removal of the maintenance window was not detected during plan.

### Steps to Reproduce

1. `terraform apply`
2. check cluster maintenance window:
    ```
    # gcloud container clusters describe myproject-europe-west1-cluster --zone europe-west1-b | grep -A4 maintenance
    maintenancePolicy:
      window:
        dailyMaintenanceWindow:
          duration: PT4H0M0S
          startTime: 08:00
    ```
3. remove maintenance window using gcloud ([cannot be removed using web console, selecting `Any time` does nothing](https://issuetracker.google.com/issues/110373172)):
    ```
    # gcloud container clusters update myproject-europe-west1-cluster --zone europe-west1-b --maintenance-window None
    ```
4. check cluster maintenance window:
    ```
    # gcloud container clusters describe myproject-europe-west1-cluster --zone europe-west1-b | grep -A4 maintenance
    ```
5. `terraform plan`

### Important Factoids

N/A

### References

N/A
