### ISSUE TITLE
Clear only operates on computed keys - secondary_ip_range is not one

### ISSUE THREAD

**Issue by pdecat** [terraform-providers/terraform-provider-google#3477]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

```
# terraform version
Terraform v0.11.13
+ provider.google v2.5.1
+ provider.google-beta v2.5.1
```

Same issue with google and google-beta 2.5.0.

Downgrading to 2.4.0 works.

### Affected Resource(s)

* `google_compute_subnetwork`

### Terraform Configuration Files

```tf
resource "google_compute_subnetwork" "subnet0" {
  name = "myproject-preprod-europe-west1-subnet0"

  network       = "https://www.googleapis.com/compute/v1/projects/myproject-preprod/global/networks/myproject-preprod-net0"
  ip_cidr_range = "10.118.128.160/28"

  secondary_ip_range {
    range_name    = "myproject-preprod-europe-west1-subnet0-secondary-range-0"
    ip_cidr_range = "10.132.0.0/14"
  }

  secondary_ip_range {
    range_name    = "myproject-preprod-europe-west1-subnet0-secondary-range-1"
    ip_cidr_range = "10.129.0.0/16"
  }

  // Enable Private Google Access to allow pods to access Google APIs without public IP addresses
  // cf. https://cloud.google.com/vpc/docs/private-access-options#pga-supported
  private_ip_google_access = "true"
}

resource "google_compute_subnetwork" "subnet1" {
  name = "myproject-preprod-europe-west1-subnet1"

  network       = "https://www.googleapis.com/compute/v1/projects/myproject-preprod/global/networks/myproject-preprod-net0"
  ip_cidr_range = "172.16.16.0/20"

  secondary_ip_range {
    range_name    = "myproject-preprod-europe-west1-subnet1-secondary-range-0"
    ip_cidr_range = "10.140.0.0/14"
  }

  secondary_ip_range {
    range_name    = "myproject-preprod-europe-west1-subnet1-secondary-range-1"
    ip_cidr_range = "10.137.0.0/16"
  }

  // Enable Private Google Access to allow pods to access Google APIs without public IP addresses
  // cf. https://cloud.google.com/vpc/docs/private-access-options#pga-supported
  private_ip_google_access = "true"
}
```

### Debug Output

https://gist.github.com/pdecat/673f5e7ffb290322b6fe4182469a62f5

### Panic Output

N/A

### Expected Behavior

`terraform plan -target module.net0.google_compute_subnetwork.subnet1` should detect no change. 

### Actual Behavior

The following error occurs:
```
* module.net0.google_compute_subnetwork.subnet1: 1 error occurred:
        * Clear only operates on computed keys - secondary_ip_range is not one
```

### Steps to Reproduce

1. `terraform plan -target module.net0.google_compute_subnetwork.subnet1`

### Important Factoids

That's maybe new behavior introduced by using the terraform 0.12 SDK with terraform 0.11.13.

In the same module, there's a similarly configured `subnet0` resource that's not affected:

```
# terraform plan -target module.net0.google_compute_subnetwork.subnet0
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

google_compute_network.net0: Refreshing state... (ID: myproject-preprod-net0)
google_compute_subnetwork.subnet0: Refreshing state... (ID: europe-west1/myproject-preprod-europe-west1-subnet0)

------------------------------------------------------------------------

No changes. Infrastructure is up-to-date.

This means that Terraform did not detect any differences between your
configuration and real physical resources that exist. As a result, no
actions need to be performed.
```

### References

* https://github.com/terraform-providers/terraform-provider-google/pull/1772/files#diff-c00013899b923b404c727949952f35ffR195
* https://github.com/terraform-providers/terraform-provider-google/commit/8279ae67dd5d334a8938ccf68d645f807ea4e852#diff-c00013899b923b404c727949952f35ffL120

**Comment by pdecat** [comment]
The order of the secondary ranges returned by the Google API is reversed for `subnet1`:
```
# gcloud --project=myproject-preprod compute networks subnets describe myproject-preprod-europe-west1-subnet1 --region europe-west1
creationTimestamp: '2016-11-04T07:10:41.813-07:00'
fingerprint: AVPZ0iZ03Ks=
gatewayAddress: 172.16.16.1
id: '123456789'
ipCidrRange: 172.16.16.0/20
kind: compute#subnetwork
name: myproject-preprod-europe-west1-subnet1
network: https://www.googleapis.com/compute/v1/projects/myproject-preprod/global/networks/myproject-preprod-net0
privateIpGoogleAccess: true
region: https://www.googleapis.com/compute/v1/projects/myproject-preprod/regions/europe-west1
secondaryIpRanges:
- ipCidrRange: 10.137.0.0/16
  rangeName: myproject-preprod-europe-west1-subnet1-secondary-range-1
- ipCidrRange: 10.140.0.0/14
  rangeName: myproject-preprod-europe-west1-subnet1-secondary-range-0
selfLink: https://www.googleapis.com/compute/v1/projects/myproject-preprod/regions/europe-west1/subnetworks/myproject-preprod-europe-west1-subnet1
```

For subnet1:
```
# gcloud --project=myproject-preprod compute networks subnets describe myproject-preprod-europe-west1-subnet0 --region europe-west1
creationTimestamp: '2016-10-17T06:51:43.384-07:00'
fingerprint: 4NbXjznut0c=
gatewayAddress: 10.118.128.161
id: '123456789'
ipCidrRange: 10.118.128.160/28
kind: compute#subnetwork
name: myproject-preprod-europe-west1-subnet0
network: https://www.googleapis.com/compute/v1/projects/myproject-preprod/global/networks/myproject-preprod-net0
privateIpGoogleAccess: true
region: https://www.googleapis.com/compute/v1/projects/myproject-preprod/regions/europe-west1
secondaryIpRanges:
- ipCidrRange: 10.132.0.0/14
  rangeName: myproject-preprod-europe-west1-subnet0-secondary-range-0
- ipCidrRange: 10.129.0.0/16
  rangeName: myproject-preprod-europe-west1-subnet0-secondary-range-1
selfLink: https://www.googleapis.com/compute/v1/projects/myproject-preprod/regions/europe-west1/subnetworks/myproject-preprod-europe-west1-subnet0
```
