### ISSUE TITLE
google_compute_instance_template additional disk created with disk_type="ssd" instead of "pd-standard"

### ISSUE THREAD

**Issue by honnibal** [terraform-providers/terraform-provider-google#4386]
Hi all,

I have a pretty confusing error, so I'm not sure I'm diagnosing this correctly. Apologies in advance if I send the discussion down the wrong track. I'm starting to think this must be a GCP issue, but I'll post this anyway just in case.

I have an instance group with a template that specifies two additional disks. One of them is a scratch disk I've configured like this:

```
  disk {
    boot = false
    auto_delete = true
    type = "SCRATCH"
    disk_size_gb = "32"
    mode = "READ_WRITE"
    device_name = "scratch"
    disk_type = "pd-standard"
  }
```

After I apply, the template is coming back with `disk_type="local-ssd"`. The instances then fail to launch, because the specified size is below the minimum for local ssds.

Terraform seems to plan the resource correctly:

```
      ~ disk {
            auto_delete  = true
            boot         = false
            device_name  = "scratch"
            disk_size_gb = 32
            disk_type    = "pd-standard"
          ~ interface    = "SCSI" -> (known after apply)
            mode         = "READ_WRITE"
          + source_image = (known after apply)
            type         = "SCRATCH"
        }
```

And indeed, when I describe the template via the gcloud command line, it's correct:

```
  - autoDelete: true
    deviceName: scratch
    index: 1
    initializeParams:
      diskSizeGb: '32'
      diskType: pd-standard
    interface: SCSI
    kind: compute#attachedDisk
    mode: READ_WRITE
    type: SCRATCH
```

And yet when I look at the GCP console, the instance template shows 
![Screenshot_2019-09-02 Compute Engine - nebula-internal - Google Cloud Platform](https://user-images.githubusercontent.com/8059750/64105324-4fca3e00-cd76-11e9-9617-43e02a0c220a.png)
