### ISSUE TITLE
Region Autoscaler on stackdriver metrics w/ Region Group manager

### ISSUE THREAD

**Issue by vmarchaud** [terraform-providers/terraform-provider-google#4916]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

```
Terraform v0.12.10
+ provider.google v2.19.0
+ provider.google-beta v2.20.0
```

### Affected Resource(s)

* google_compute_region_autoscaler

### Terraform Configuration Files

```tf
resource "google_compute_region_instance_group_manager" "redis_group" {
  name = "redis-instance-${var.cluster_name}"

  base_instance_name         =  "redis-instance-group-${var.cluster_name}"
  
  region                     =  "${var.region}"
  distribution_policy_zones  =  var.zones

  version {
    instance_template        =  "${google_compute_instance_template.redis.self_link}"
  }

  named_port {
    name = "custom"
    port = 6379
  }

  auto_healing_policies {
    health_check      = "${google_compute_health_check.redis_healthcheck.self_link}"
    initial_delay_sec = 120
  }
}

resource "google_compute_region_autoscaler" "redis_autoscaler" {
  provider  = "google-beta"
  name      = "redis-autoscaler"
  target    = "${google_compute_region_instance_group_manager.redis_group.self_link}"

  autoscaling_policy {
    max_replicas    = "${var.max_redis_replica_count}"
    min_replicas    = "${var.min_redis_replica_count}"
    cooldown_period = 60

    metric {
      name    = "agent.googleapis.com/memory/percent_used"
      target  = "80"
      filter  = "metric.label.state=\"used\""
      type    = "GAUGE"
    }
  }
}
```

### Debug Output

```
Error: Error updating RegionAutoscaler "europe-west1/redis-autoscaler": googleapi: Error 412: Regional managed instance groups do not support autoscaling using per-group metrics., conditionNotMet

  on main.tf line 208, in resource "google_compute_region_autoscaler" "redis_autoscaler":
 208: resource "google_compute_region_autoscaler" "redis_autoscaler" {
```

### Expected Behavior

The Autoscaler should create correctly since the metric is a GCE metric so not a `per-group metric` like the output say. The zonal autoscaler have the possiblity to specify the `scope` of a metric but no on the regional autoscaler.

### Actual Behavior

It fail to create the regional metrics since we can't specify the `scope` of the metric and it supposes that the metric is `per-group`.

### Steps to Reproduce

1. Create a `instance_template`
2. Create a `region_instance_group_manager` and link it to the `instance_template`
3. Add a autoscaler on a stackdriver metrics

1. `terraform apply`

**Comment by vmarchaud** [comment]
Note that it work correctly from the UI, i can set `agent.googleapis.com/memory/percent_used` as a metric for autoscaling.

**Comment by venkykuberan** [comment]
@vmarchaud sorry for the delay in response. Somehow this issue fell through the cracks. 

**Regional managed instance groups do not support autoscaling using per-group metrics** as per the [doc](https://cloud.google.com/compute/docs/autoscaler/scaling-stackdriver-monitoring-metrics#per_group_metrics). I get the same error on the UI as well. However you can create Autoscaling per-group metrics for single zone instance groups.

**Comment by vmarchaud** [comment]
I can totally set it with a regional autoscaler via the UI (it saved without an error) even though i'm not actually sure it's working:
![image](https://user-images.githubusercontent.com/2820968/71618427-ce69a780-2bbf-11ea-8216-96e29db81aa4.png)

What's the procedure to ask for this feature ?

**Comment by venkykuberan** [comment]
@vmarchaud can you please verify the following to confirm your resources are created as expected. 

1. Click on the Notifications icon (top right on the UI) and see if you get any error for the instance group creation
2. Describe the resource you created in gcloud and verify it shows the autoscaling and metrics info
 ``` gcloud compute instance-groups describe <your_instance_group> --region="<your_region>" ```

**Comment by vmarchaud** [comment]
@venkykuberan 
1. See screenshot i can totally create it via the UI:
![image](https://user-images.githubusercontent.com/2820968/71715900-424fbe00-2e13-11ea-98b4-31322a239655.png)

2. Here the output of `gcloud compute instance-groups managed describe test --region europe-west-1` (i've redacted the project id):

```
autoscaler:
  autoscalingPolicy:
    coolDownPeriodSec: 60
    customMetricUtilizations:
    - metric: agent.googleapis.com/agent/memory_usage
      utilizationTarget: 10.0
      utilizationTargetType: GAUGE
    maxNumReplicas: 3
    minNumReplicas: 1
    mode: ON
  creationTimestamp: '2020-01-03T01:22:21.913-08:00'
  id: '6121233022149900579'
  kind: compute#autoscaler
  name: test
  recommendedSize: 1
  region: https://www.googleapis.com/compute/v1/projects/<project>/regions/europe-west1
  selfLink: https://www.googleapis.com/compute/v1/projects/<project>/regions/europe-west1/autoscalers/test
  status: ACTIVE
  statusDetails:
  - message: There was no data received for the monitoring metric(s) configured for
      autoscaling. Please check that the metrics were configured correctly.
    type: MISSING_CUSTOM_METRIC_DATA_POINTS
  target: https://www.googleapis.com/compute/v1/projects/<project>/regions/europe-west1/instanceGroupManagers/test
baseInstanceName: test
creationTimestamp: '2020-01-03T01:21:59.200-08:00'
currentActions:
  abandoning: 0
  creating: 0
  creatingWithoutRetries: 0
  deleting: 0
  none: 1
  recreating: 0
  refreshing: 0
  restarting: 0
  verifying: 0
distributionPolicy:
  zones:
  - zone: https://www.googleapis.com/compute/v1/projects/<project>/zones/europe-west1-b
  - zone: https://www.googleapis.com/compute/v1/projects/<project>/zones/europe-west1-c
  - zone: https://www.googleapis.com/compute/v1/projects/<project>/zones/europe-west1-d
fingerprint: v4d6ayz5ksk=
id: '4605659021828077912'
instanceGroup: https://www.googleapis.com/compute/v1/projects/<project>/regions/europe-west1/instanceGroups/test
instanceTemplate: https://www.googleapis.com/compute/v1/projects/<project>/global/instanceTemplates/terraform-20200102110223633200000002
kind: compute#instanceGroupManager
name: test
region: https://www.googleapis.com/compute/v1/projects/<project>/regions/europe-west1
selfLink: https://www.googleapis.com/compute/v1/projects/<project>/regions/europe-west1/instanceGroupManagers/test
status:
  isStable: true
  versionTarget:
    isReached: true
targetSize: 1
updatePolicy:
  instanceRedistributionType: PROACTIVE
  maxSurge:
    calculated: 3
    fixed: 3
  maxUnavailable:
    calculated: 3
    fixed: 3
  minimalAction: REPLACE
  type: OPPORTUNISTIC
versions:
- instanceTemplate: https://www.googleapis.com/compute/v1/projects/<project>/global/instanceTemplates/terraform-20200102110223633200000002
  targetSize:
    calculated: 1
```
I believe the error comes from the fact that i specified a wrong metric (or that it didn't found any value since i just started the instances), i already had it working with my previous comment's screenshot.

> Regional managed instance groups do not support autoscaling using per-group metrics
Note that i'm using `per-instance` metric and not `per-group`, so i believe it should be supported in my case.
