### ISSUE TITLE
google_app_engine_standard_app_version ModuleNotFoundError: No module named 'hello_world.wsgi'" 

### ISSUE THREAD

**Issue by jjorissen52** [terraform-providers/terraform-provider-google#5192]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version
```
Terraform v0.12.10
+ provider.archive v1.3.0
+ provider.google v3.2.0
+ provider.local v1.4.0
+ provider.null v2.1.2
```

### Affected Resource(s)

* google_app_engine_standard_app_version

### Terraform Configuration Files

```tf
data "archive_file" "hello_world_source" {
  type        = "zip"
  source_dir = "${path.module}/../../application/hello_world"
  output_path = "${path.module}/../extras/hello_world.zip"
}

resource "google_storage_bucket" "deployment_config" {
  bucket_policy_only = true
  force_destroy      = true
  name               = "deployment-config-${var.project.number}"
  requester_pays     = false
  storage_class      = "STANDARD"
}

resource "google_storage_bucket_object" "hello_world_zip" {
    source = "${path.module}/../extras/hello_world.zip"
    bucket = "${google_storage_bucket.deployment_config.name}"
    name = "hello_world.zip"

    # archive must exist first
    depends_on = ["data.archive_file.hello_world_source"]
}

resource "google_app_engine_standard_app_version" "hello_world" {
#   version_id = "v1"
  version_id = "${data.archive_file.hello_world_source.output_md5}"
  service    = "default"
  runtime    = "python37"

  entrypoint {
    shell = "gunicorn -b :$PORT hello_world.wsgi --log-level=DEBUG"
  }

  deployment {
    zip {
      source_url = "https://storage.googleapis.com/${google_storage_bucket.deployment_config.name}/${google_storage_bucket_object.hello_world_zip.name}"
    }
  }
  noop_on_destroy = true
  # archive must exist first
  depends_on = ["google_storage_bucket_object.hello_world_zip"]
}
```

### Debug Output
Terraform creates version successfully, but the resulting App Engine instances are incapable of launching the wsgi server. The below image says that it cannot find the wsgi module
![image](https://user-images.githubusercontent.com/12461302/70942218-cb918300-2013-11ea-9b94-8c703167d833.png)

But the source for the application shows that it's there.
![image](https://user-images.githubusercontent.com/12461302/70943448-8884df00-2016-11ea-8eb0-0295bf0f076d.png)

### Expected Behavior
When I visit the app engine deployment, I should see the DisallowedHost Django debug page, which indicates that a Django app is running.

### Actual Behavior
 I get 502 bad gateway from NGINX.

### Steps to Reproduce
1. install python 3.7
2. `pip install Django gunicorn`
3. `django-admin startproject hello_world`
4. `cd hello_world && gunicorn hello_world.wsgi # application starts`
5. visit localhost:8000 and see the default launch page
6. `^c # stop gunicorn`
7. `echo -e "Django\ngunicorn" > requirements.txt # add requirements file`
8. `terraform apply`
9. visit default deployment url, get 502.

### Important Factoids
If I add the below `app.yaml` and run `gcloud app deploy` in the `hello_world` Django app created above, the app works as expected (shows "DisallowedHost" screen, as it should). 

```yaml
runtime: python37
entrypoint: gunicorn -b :$PORT hello_world.wsgi --log-level=DEBUG

handlers:
# This configures Google App Engine to serve the files in the app's static
# directory.
- url: /static
  static_dir: static/

# This handler routes all requests not caught above to your main app. It is
# required when static routes are defined, but can be omitted (along with
# the entire handlers section) when there are no static files defined.
- url: /.*
  script: auto
```
