### ISSUE TITLE
Can't avoid hardcoding interface:scsi

### ISSUE THREAD

**Issue by jsoref** [terraform-providers/terraform-provider-google#5295]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

```
Terraform v0.12.16
+ provider.google v3.3.0
```

### Affected Resource(s)

* google_compute_instance_template

### Terraform Configuration Files

```tf
provider google {
  version = "~> 3.0"
}

resource "google_compute_instance_template" "node" {
  name         = "node"
  machine_type = "n1-standard-1"
  can_ip_forward = false

  disk {
    source_image = "https://www.googleapis.com/compute/v1/projects/debian-cloud/global/images/family/debian-9"
    disk_size_gb = 10
    disk_type    = "pd-ssd"
    boot         = true
    mode         = "READ_WRITE"
    type         = "PERSISTENT"
  }

  network_interface {
    network = "default"
  }
}

resource "google_compute_instance_template" "node-scsi" {
  name         = "node-scsi"
  machine_type = "n1-standard-1"
  can_ip_forward = false

  disk {
    source_image = "https://www.googleapis.com/compute/v1/projects/debian-cloud/global/images/family/debian-9"
    disk_size_gb = 10
    disk_type    = "pd-ssd"
    boot         = true
    mode         = "READ_WRITE"
    type         = "PERSISTENT"
    interface    = "SCSI"
  }

  network_interface {
    network = "default"
  }
}
```

### Expected Behavior

A similarly manually created template doesn't declare a scsi interface -- which to me means that in theory it could change if google updates their defaults (which is perhaps something i might want):

```
creationTimestamp: '...'
description: ''
id: '...'
kind: compute#instanceTemplate
name: node-native
properties:
  canIpForward: false
  disks:
  - autoDelete: true
    boot: true
    deviceName: boot
    index: 0
    initializeParams:
      diskSizeGb: '10'
      diskType: pd-ssd
      sourceImage: https://www.googleapis.com/compute/v1/projects/debian-cloud/global/images/family/debian-9
    kind: compute#attachedDisk
    mode: READ_WRITE
    type: PERSISTENT
  machineType: n1-standard-1
  metadata:
    fingerprint: ...
    kind: compute#metadata
  networkInterfaces:
  - kind: compute#networkInterface
    network: https://www.googleapis.com/compute/v1/projects/.../global/networks/default
  scheduling:
    automaticRestart: true
    onHostMaintenance: MIGRATE
    preemptible: false
  serviceAccounts:
  - email: 552057127791-compute@developer.gserviceaccount.com
    scopes:
    - https://www.googleapis.com/auth/devstorage.read_only
    - https://www.googleapis.com/auth/logging.write
    - https://www.googleapis.com/auth/monitoring.write
    - https://www.googleapis.com/auth/service.management.readonly
    - https://www.googleapis.com/auth/servicecontrol
    - https://www.googleapis.com/auth/trace.append
selfLink: https://www.googleapis.com/compute/v1/projects/.../global/instanceTemplates/node-native
```

### Actual Behavior

plan output:
```
Terraform will perform the following actions:

  # google_compute_instance_template.node will be created
  + resource "google_compute_instance_template" "node" {
      + can_ip_forward       = false
      + id                   = (known after apply)
      + machine_type         = "n1-standard-1"
      + metadata_fingerprint = (known after apply)
      + name                 = "node"
      + name_prefix          = (known after apply)
      + project              = (known after apply)
      + region               = (known after apply)
      + self_link            = (known after apply)
      + tags_fingerprint     = (known after apply)

      + disk {
          + auto_delete  = true
          + boot         = true
          + device_name  = (known after apply)
          + disk_size_gb = 10
          + disk_type    = "pd-ssd"
          + interface    = (known after apply)
          + mode         = "READ_WRITE"
          + source_image = "https://www.googleapis.com/compute/v1/projects/debian-cloud/global/images/family/debian-9"
          + type         = "PERSISTENT"
        }

      + network_interface {
          + network            = "default"
          + subnetwork         = (known after apply)
          + subnetwork_project = (known after apply)
        }

      + scheduling {
          + automatic_restart   = (known after apply)
          + on_host_maintenance = (known after apply)
          + preemptible         = (known after apply)

          + node_affinities {
              + key      = (known after apply)
              + operator = (known after apply)
              + values   = (known after apply)
            }
        }
    }

  # google_compute_instance_template.node-scsi will be created
  + resource "google_compute_instance_template" "node-scsi" {
      + can_ip_forward       = false
      + id                   = (known after apply)
      + machine_type         = "n1-standard-1"
      + metadata_fingerprint = (known after apply)
      + name                 = "node-scsi"
      + name_prefix          = (known after apply)
      + project              = (known after apply)
      + region               = (known after apply)
      + self_link            = (known after apply)
      + tags_fingerprint     = (known after apply)

      + disk {
          + auto_delete  = true
          + boot         = true
          + device_name  = (known after apply)
          + disk_size_gb = 10
          + disk_type    = "pd-ssd"
          + interface    = "SCSI"
          + mode         = "READ_WRITE"
          + source_image = "https://www.googleapis.com/compute/v1/projects/debian-cloud/global/images/family/debian-9"
          + type         = "PERSISTENT"
        }

      + network_interface {
          + network            = "default"
          + subnetwork         = (known after apply)
          + subnetwork_project = (known after apply)
        }

      + scheduling {
          + automatic_restart   = (known after apply)
          + on_host_maintenance = (known after apply)
          + preemptible         = (known after apply)

          + node_affinities {
              + key      = (known after apply)
              + operator = (known after apply)
              + values   = (known after apply)
            }
        }
    }
```

describe output:
```
$ gcloud compute instance-templates describe node
creationTimestamp: '...'
description: ''
id: '...'
kind: compute#instanceTemplate
name: node
properties:
  disks:
  - autoDelete: true
    boot: true
    deviceName: persistent-disk-0
    index: 0
    initializeParams:
      diskSizeGb: '10'
      diskType: pd-ssd
      sourceImage: https://www.googleapis.com/compute/v1/projects/debian-cloud/global/images/family/debian-9
    interface: SCSI
    kind: compute#attachedDisk
    mode: READ_WRITE
    type: PERSISTENT
  machineType: n1-standard-1
  metadata:
    fingerprint: JTqYaJW_BVs=
    kind: compute#metadata
  networkInterfaces:
  - kind: compute#networkInterface
    network: https://www.googleapis.com/compute/v1/projects/.../global/networks/default
  scheduling:
    automaticRestart: true
    onHostMaintenance: MIGRATE
    preemptible: false
selfLink: https://www.googleapis.com/compute/v1/projects/.../global/instanceTemplates/node

$ gcloud compute instance-templates describe node-scsi
creationTimestamp: '...'
description: ''
id: '...'
kind: compute#instanceTemplate
name: node-scsi
properties:
  disks:
  - autoDelete: true
    boot: true
    deviceName: persistent-disk-0
    index: 0
    initializeParams:
      diskSizeGb: '10'
      diskType: pd-ssd
      sourceImage: https://www.googleapis.com/compute/v1/projects/debian-cloud/global/images/family/debian-9
    interface: SCSI
    kind: compute#attachedDisk
    mode: READ_WRITE
    type: PERSISTENT
  machineType: n1-standard-1
  metadata:
    fingerprint: JTqYaJW_BVs=
    kind: compute#metadata
  networkInterfaces:
  - kind: compute#networkInterface
    network: https://www.googleapis.com/compute/v1/projects/.../global/networks/default
  scheduling:
    automaticRestart: true
    onHostMaintenance: MIGRATE
    preemptible: false
selfLink: https://www.googleapis.com/compute/v1/projects/.../global/instanceTemplates/node-scsi
```
### Steps to Reproduce

1. `terraform apply`
1. `gcloud compute instance-templates describe node-native`
1. `gcloud compute instance-templates describe node`
1. `gcloud compute instance-templates describe node-scsi`

### Important Factoids

I have pre-existing manually created templates that I kind of like. I'd like to migrate to using terraform w/o losing their characteristics.

(Yes, I understand SCSI is the default today, and the terraform behavior is documented, but it clearly isn't required from gcloud's perspective.)

### References

This is in the family of #5283 -- things which do not quite work the way I'd like in that I can't produce the output I'd like the way I'd like / there doesn't appear to be any way to do so using terraform.
