### ISSUE TITLE
autoprovisioning scopes are wrong with service account

### ISSUE THREAD

**Issue by mtricolici** [terraform-providers/terraform-provider-google#5545]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v0.12.20
+ provider.google v3.5.0
+ provider.google-beta v3.5.0
+ provider.kubernetes v1.10.0

### Affected Resource(s)

* google_container_cluster

### Terraform Configuration Files

```tf
resource "google_container_cluster" "test1" {
  provider = google-beta
...
  node_config {
    service_account = "zuzu@myproject.iam.gserviceaccount.com"
    metadata = {
      disable-legacy-endpoints = "true"
    }
  }
...
  cluster_autoscaling {
    enabled = true

    resource_limits {
      resource_type = "cpu"
      minimum = 1
      maximum = 1
    }

    resource_limits {
      resource_type = "memory"
      minimum = 20
      maximum = 20
    }
    auto_provisioning_defaults {
      service_account = "zuzu@myproject.iam.gserviceaccount.com"
   }
  }
```

### Expected Behavior

A cluster like this should be created (this one was created via gcloud commands):
```
gcloud container node-pools describe default-pool --cluster=created-from-ui --zone us-central1-c
autoscaling: {}
config:
  diskSizeGb: 100
  diskType: pd-standard
  imageType: COS
  machineType: n1-standard-1
  metadata:
    disable-legacy-endpoints: 'true'
  oauthScopes:
  - https://www.googleapis.com/auth/cloud-platform
  serviceAccount: zuzu@myproject.iam.gserviceaccount.com
```

### Actual Behavior
oauthScopes defaults are wrong. Via terraform we can't set/adjust them.
```
gcloud container node-pools describe default-pool --cluster=created-from-terraform --zone us-central1-c
config:
  diskSizeGb: 100
  diskType: pd-standard
  imageType: COS
  machineType: n1-standard-1
  metadata:
    disable-legacy-endpoints: 'true'
  oauthScopes:
  - https://www.googleapis.com/auth/logging.write
  - https://www.googleapis.com/auth/monitoring
  serviceAccount: zuzu@myproject.iam.gserviceaccount.com
```

### Steps to Reproduce

1. `terraform apply`

* #0000
