### ISSUE TITLE
Is there any way to launch instance form GCP market place

### ISSUE THREAD

**Issue by venkat44488** [terraform-providers/terraform-provider-google#5695]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### New or Affected Resource(s)

* google_XXXXX

### Potential Terraform Configuration

```tf
# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent.
```

### References

* #0000

**Comment by bdronneau** [comment]
Hi,

Something like ?
```hcl
resource "google_compute_instance" "default" {
  name         = "tf-test"
  machine_type = "n1-standard-1"
  zone         = "europe-west1-c"

  tags = ["foo", "bar"]

  boot_disk {
    initialize_params {
      image = "bitnami-launchpad/bitnami-rabbitmq-3-8-2-3-r01-linux-debian-9-x86-64-nami"
    }
  }

  network_interface {
    network = "default"

    access_config {}
  }

  metadata = {
    foo = "bar"
  }
}
```

Instance generated:
```yaml
canIpForward: false
cpuPlatform: Intel Haswell
creationTimestamp: '2020-02-20T03:03:19.139-08:00'
deletionProtection: false
disks:
- autoDelete: true
  boot: true
  deviceName: persistent-disk-0
  diskSizeGb: '10'
  index: 0
  interface: SCSI
  kind: compute#attachedDisk
  licenses:
  - https://www.googleapis.com/compute/v1/projects/debian-cloud/global/licenses/debian-9-stretch
  - https://www.googleapis.com/compute/v1/projects/bitnami-launchpad/global/licenses/bitnami-rabbitmq
  mode: READ_WRITE
  source: https://www.googleapis.com/compute/v1/projects/<project>/zones/europe-west1-c/disks/tf-test
  type: PERSISTENT
id: 'XXXX'
kind: compute#instance
labelFingerprint: X.X.X.X
machineType: https://www.googleapis.com/compute/v1/projects/<project>/zones/europe-west1-c/machineTypes/n1-standard-1
metadata:
  fingerprint: XXXXXXXXXXXXX=
  items:
  - key: foo
    value: bar
  kind: compute#metadata
name: tf-test
networkInterfaces:
- accessConfigs:
  - kind: compute#accessConfig
    name: external-nat
    natIP:  X.X.X.X
    networkTier: PREMIUM
    type: ONE_TO_ONE_NAT
  fingerprint: XXXXXXXX
  kind: compute#networkInterface
  name: nic0
  network: https://www.googleapis.com/compute/v1/projects/<project>//global/networks/default
  networkIP: X.X.X.X
  subnetwork: https://www.googleapis.com/compute/v1/projects/<project>//regions/europe-west1/subnetworks/default
scheduling:
  automaticRestart: true
  onHostMaintenance: MIGRATE
  preemptible: false
selfLink: https://www.googleapis.com/compute/v1/projects/<project>/zones/europe-west1-c/instances/tf-test
startRestricted: false
status: RUNNING
tags:
  fingerprint: XXXXXXXXXXXXX=
  items:
  - bar
  - foo
zone: https://www.googleapis.com/compute/v1/projects/<project>/zones/europe-west1-c
```

In order to get image name:
```
gcloud compute images list --project bitnami-launchpad --no-standard-images --filter="name ~ 'rabbit.*'"
```
Project extract from marketplace URL: https://console.cloud.google.com/marketplace/details/bitnami-launchpad/rabbitmq-cluster?filter=category:developer-tools&q=rabbit&id=6710c653-a89f-4a39-bff7-eb6c54bcdbb8&project=ma-dev2&organizationId=5867207345
