### ISSUE TITLE
Cloud Armor, google_compute_security_policy, how can I add the target LB backend?

### ISSUE THREAD

**Issue by caueasantos** [terraform-providers/terraform-provider-google#6819]
@slevenick Looks like there is no possible way to use cloud armor with kubernetes_ingres. please correct me if I am wrong, Thanks

_Originally posted by @meirhazon2 in https://github.com/terraform-providers/terraform-provider-google/issues/4973#issuecomment-557690348_

**Comment by caueasantos** [comment]
Ingress won' t be handled by terraform, so make sense find new alternatives to do it through google ingress capabilities, please try to do the following:

```
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  namespace: ingress
  name: ingress-config
spec:
  securityPolicy:
    name: "cloud-armor-policy-name" --> Cloud Armor policy created by Terraform (or not)
 ```

On each service referenced by ingress include the annotation:

```
apiVersion: v1
kind: Service
metadata:
  name: service
  namespace: service-namespace
  annotations:
    cloud.google.com/backend-config: '{"default": "ingress-config"}'
```

This should be enough to add your target loadbalancers on google cloud armor
