### ISSUE TITLE
instancegroupmanager serviceaccount

### ISSUE THREAD

**Issue by danawillow** [terraform-providers/terraform-provider-google#6858]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

https://cloud.google.com/compute/docs/reference/rest/beta/instanceGroupManagers, serviceAccount field

### New or Affected Resource(s)

* google_compute_instance_group_manager
* google_compute_region_instance_group_manager

### References

* b/161907347

**Comment by upodroid** [comment]
Still bugged.

```
 REDACTED  MCW0CDP3YY  ~  $  http POST https://compute.googleapis.com/compute/beta/projects/REDACTED/regions/europe-west2/instanceGroupManagers "Authorization: Bearer $(gcloud auth print-access-token)" name=test serviceAccount=terraform@REDACTED.iam.gserviceaccount.com instanceTemplate=projects/REDACTED/global/instanceTemplates/nginx-proxy-public targetSize=0
HTTP/1.1 400 Bad Request
Alt-Svc: h3-29=":443"; ma=2592000,h3-T051=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"
Cache-Control: private
Content-Encoding: gzip
Content-Type: application/json; charset=UTF-8
Date: Fri, 04 Dec 2020 13:09:46 GMT
Server: ESF
Transfer-Encoding: chunked
Vary: Origin
Vary: X-Origin
Vary: Referer
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 0

{
    "error": {
        "code": 400,
        "errors": [
            {
                "domain": "global",
                "message": "Invalid value for field 'resource.serviceAccount': 'terraform@REDACTED.iam.gserviceaccount.com'. service account support is not yet available",
                "reason": "invalid"
            }
        ],
        "message": "Invalid value for field 'resource.serviceAccount': 'terraform@REDACTED.iam.gserviceaccount.com'. service account support is not yet available"
    }
}
```

**Comment by rileykarson** [comment]
Hey @upodroid! If you have the time, do you mind checking again?

**Comment by upodroid** [comment]
Still bugged.

```
 maha4472  MCW0CDP3YY  ~  $  http POST https://compute.googleapis.com/compute/beta/projects/REDACTED/regions/europe-west2/instanceGroupManagers "Authorization: Bearer $(gcloud auth print-access-token)" name=test serviceAccount=terraform@REDACTED.iam.gserviceaccount.com instanceTemplate=projects/REDACTED/global/instanceTemplates/nginx-proxy-public targetSize=0
HTTP/1.1 400 Bad Request
Alt-Svc: h3-29=":443"; ma=2592000,h3-T051=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"
Cache-Control: private
Content-Encoding: gzip
Content-Type: application/json; charset=UTF-8
Date: Fri, 22 Jan 2021 00:24:20 GMT
Server: ESF
Transfer-Encoding: chunked
Vary: Origin
Vary: X-Origin
Vary: Referer
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 0

{
    "error": {
        "code": 400,
        "errors": [
            {
                "domain": "global",
                "message": "Invalid value for field 'resource.serviceAccount': 'terraform@REDACTED.iam.gserviceaccount.com'. service account support is not yet available",
                "reason": "invalid"
            }
        ],
        "message": "Invalid value for field 'resource.serviceAccount': 'terraform@REDACTED.iam.gserviceaccount.com'. service account support is not yet available"
    }
}
```
However, the field does appear in the API so I can add it as computed field to close it out.

```
 REDACTED  MCW0CDP3YY  ~  $  gcloud beta compute instance-groups managed list --format yaml
---
autoscaled: no
baseInstanceName: web-mig
creationTimestamp: '2020-05-07T07:31:13.267-07:00'
currentActions:
  abandoning: 0
  creating: 0
  creatingWithoutRetries: 0
  deleting: 0
  none: 0
  recreating: 0
  refreshing: 0
  restarting: 0
  verifying: 0
distributionPolicy:
  targetShape: EVEN
  zones:
  - zone: https://www.googleapis.com/compute/beta/projects/REDACTED/zones/europe-west2-a
  - zone: https://www.googleapis.com/compute/beta/projects/REDACTED/zones/europe-west2-b
  - zone: https://www.googleapis.com/compute/beta/projects/REDACTED/zones/europe-west2-c
fingerprint: ddhAh0mYdnM=
id: '7043377863690134878'
instanceGroup: https://www.googleapis.com/compute/beta/projects/REDACTED/regions/europe-west2/instanceGroups/web-mig
instanceTemplate: https://www.googleapis.com/compute/beta/projects/REDACTED/global/instanceTemplates/nginx-proxy-public
kind: compute#instanceGroupManager
name: web-mig
namedPorts:
- name: http
  port: 80
region: https://www.googleapis.com/compute/beta/projects/REDACTED/regions/europe-west2
selfLink: https://www.googleapis.com/compute/beta/projects/REDACTED/regions/europe-west2/instanceGroupManagers/web-mig
serviceAccount: 550924169191@cloudservices.gserviceaccount.com
size: '0'
status:
  isStable: true
  stateful:
    hasStatefulConfig: false
    isStateful: false
    perInstanceConfigs:
      allEffective: true
  versionTarget:
    isReached: true
targetSize: 0
updatePolicy:
  instanceRedistributionType: NONE
  maxSurge:
    calculated: 3
    fixed: 3
  maxUnavailable:
    calculated: 3
    fixed: 3
  minReadySec: 0
  minimalAction: REPLACE
  replacementMethod: SUBSTITUTE
  type: OPPORTUNISTIC
versions:
- instanceTemplate: https://www.googleapis.com/compute/beta/projects/REDACTED/global/instanceTemplates/nginx-proxy-public
  targetSize:
    calculated: 0
```
