### ISSUE TITLE
google_memcache_instance: Cannot fetch an endpoint for memcached instance

### ISSUE THREAD

**Issue by dex4er** [terraform-providers/terraform-provider-google#6907]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

For newly created google_memcache_instance:

```tf
# google_memcache_instance.memcached-1:
resource "google_memcache_instance" "memcached-1" {
    authorized_network = "XXX"
    create_time        = "2020-08-02T12:48:21.085285616Z"
    id                 = "projects/XXX/locations/europe-west1/instances/memcached-1"
    labels             = {}
    name               = "memcached-1"
    node_count         = 1
    project            = "XXX"
    region             = "europe-west1"
    zones              = [
        "europe-west1-b",
    ]

    node_config {
        cpu_count      = 1
        memory_size_mb = 1024
    }

    timeouts {}
}
```

I miss some field that I can get with `gcloud beta memcache instances list --region=europe-west1 --format=yaml`:

```yaml
authorizedNetwork: XXX
createTime: '2020-08-02T12:48:21.085285616Z'
discoveryEndpoint: A.A.A.A:11211
memcacheFullVersion: memcached-1.5.16
memcacheNodes:
- host: A.A.A.A
  nodeId: node-b-1
  parameters: {}
  port: 11211
  state: READY
  zone: europe-west1-b
memcacheVersion: MEMCACHE_1_5
name: projects/XXX/locations/europe-west1/instances/memcached-1
nodeConfig:
  cpuCount: 1
  memorySizeMb: 1024
nodeCount: 1
parameters: {}
state: READY
updateTime: '2020-08-02T12:53:20.073848397Z'
zones:
- europe-west1-b
```

The most important is of course `discoveryEndpoint` and `memcacheNodes[].host` that I would like to use as a parameter for another resource.

Additionally I think it would be good to have data source for memcached instances then I could fetch the endpoint endpoint from one GCP project to another.

### New or Affected Resource(s)

* google_memcache_instance

### References

* #0000
